// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: conf/budget_ui.proto

package com.digitald4.budget.proto;

public final class BudgetUIProtos {
  private BudgetUIProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TemplateUIOrBuilder extends
      // @@protoc_insertion_point(interface_extends:budget.TemplateUI)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>optional int32 portfolio_id = 2;</code>
     */
    boolean hasPortfolioId();
    /**
     * <code>optional int32 portfolio_id = 2;</code>
     */
    int getPortfolioId();

    /**
     * <code>optional string name = 3;</code>
     */
    boolean hasName();
    /**
     * <code>optional string name = 3;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 3;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string description = 4;</code>
     */
    boolean hasDescription();
    /**
     * <code>optional string description = 4;</code>
     */
    java.lang.String getDescription();
    /**
     * <code>optional string description = 4;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();
  }
  /**
   * Protobuf type {@code budget.TemplateUI}
   */
  public  static final class TemplateUI extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:budget.TemplateUI)
      TemplateUIOrBuilder {
    // Use TemplateUI.newBuilder() to construct.
    private TemplateUI(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private TemplateUI() {
      id_ = 0;
      portfolioId_ = 0;
      name_ = "";
      description_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TemplateUI(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              portfolioId_ = input.readInt32();
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              name_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              description_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.digitald4.budget.proto.BudgetUIProtos.internal_static_budget_TemplateUI_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.digitald4.budget.proto.BudgetUIProtos.internal_static_budget_TemplateUI_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.digitald4.budget.proto.BudgetUIProtos.TemplateUI.class, com.digitald4.budget.proto.BudgetUIProtos.TemplateUI.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>optional int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int PORTFOLIO_ID_FIELD_NUMBER = 2;
    private int portfolioId_;
    /**
     * <code>optional int32 portfolio_id = 2;</code>
     */
    public boolean hasPortfolioId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 portfolio_id = 2;</code>
     */
    public int getPortfolioId() {
      return portfolioId_;
    }

    public static final int NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 3;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string name = 3;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 4;
    private volatile java.lang.Object description_;
    /**
     * <code>optional string description = 4;</code>
     */
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string description = 4;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          description_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string description = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, portfolioId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, name_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, description_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, portfolioId_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, name_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, description_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateUI parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateUI parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateUI parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateUI parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateUI parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateUI parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateUI parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateUI parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateUI parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateUI parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.digitald4.budget.proto.BudgetUIProtos.TemplateUI prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code budget.TemplateUI}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:budget.TemplateUI)
        com.digitald4.budget.proto.BudgetUIProtos.TemplateUIOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.digitald4.budget.proto.BudgetUIProtos.internal_static_budget_TemplateUI_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.digitald4.budget.proto.BudgetUIProtos.internal_static_budget_TemplateUI_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.digitald4.budget.proto.BudgetUIProtos.TemplateUI.class, com.digitald4.budget.proto.BudgetUIProtos.TemplateUI.Builder.class);
      }

      // Construct using com.digitald4.budget.proto.BudgetUIProtos.TemplateUI.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        portfolioId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        description_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.digitald4.budget.proto.BudgetUIProtos.internal_static_budget_TemplateUI_descriptor;
      }

      public com.digitald4.budget.proto.BudgetUIProtos.TemplateUI getDefaultInstanceForType() {
        return com.digitald4.budget.proto.BudgetUIProtos.TemplateUI.getDefaultInstance();
      }

      public com.digitald4.budget.proto.BudgetUIProtos.TemplateUI build() {
        com.digitald4.budget.proto.BudgetUIProtos.TemplateUI result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.digitald4.budget.proto.BudgetUIProtos.TemplateUI buildPartial() {
        com.digitald4.budget.proto.BudgetUIProtos.TemplateUI result = new com.digitald4.budget.proto.BudgetUIProtos.TemplateUI(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.portfolioId_ = portfolioId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.description_ = description_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.digitald4.budget.proto.BudgetUIProtos.TemplateUI) {
          return mergeFrom((com.digitald4.budget.proto.BudgetUIProtos.TemplateUI)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.digitald4.budget.proto.BudgetUIProtos.TemplateUI other) {
        if (other == com.digitald4.budget.proto.BudgetUIProtos.TemplateUI.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasPortfolioId()) {
          setPortfolioId(other.getPortfolioId());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000004;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasDescription()) {
          bitField0_ |= 0x00000008;
          description_ = other.description_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.digitald4.budget.proto.BudgetUIProtos.TemplateUI parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.digitald4.budget.proto.BudgetUIProtos.TemplateUI) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>optional int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private int portfolioId_ ;
      /**
       * <code>optional int32 portfolio_id = 2;</code>
       */
      public boolean hasPortfolioId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 portfolio_id = 2;</code>
       */
      public int getPortfolioId() {
        return portfolioId_;
      }
      /**
       * <code>optional int32 portfolio_id = 2;</code>
       */
      public Builder setPortfolioId(int value) {
        bitField0_ |= 0x00000002;
        portfolioId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 portfolio_id = 2;</code>
       */
      public Builder clearPortfolioId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        portfolioId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 3;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>optional string description = 4;</code>
       */
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string description = 4;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            description_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string description = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string description = 4;</code>
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string description = 4;</code>
       */
      public Builder clearDescription() {
        bitField0_ = (bitField0_ & ~0x00000008);
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>optional string description = 4;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        description_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:budget.TemplateUI)
    }

    // @@protoc_insertion_point(class_scope:budget.TemplateUI)
    private static final com.digitald4.budget.proto.BudgetUIProtos.TemplateUI DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.digitald4.budget.proto.BudgetUIProtos.TemplateUI();
    }

    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateUI getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<TemplateUI>
        PARSER = new com.google.protobuf.AbstractParser<TemplateUI>() {
      public TemplateUI parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new TemplateUI(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<TemplateUI> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TemplateUI> getParserForType() {
      return PARSER;
    }

    public com.digitald4.budget.proto.BudgetUIProtos.TemplateUI getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TemplateListRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:budget.TemplateListRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 portfolio_id = 1;</code>
     */
    boolean hasPortfolioId();
    /**
     * <code>optional int32 portfolio_id = 1;</code>
     */
    int getPortfolioId();
  }
  /**
   * Protobuf type {@code budget.TemplateListRequest}
   */
  public  static final class TemplateListRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:budget.TemplateListRequest)
      TemplateListRequestOrBuilder {
    // Use TemplateListRequest.newBuilder() to construct.
    private TemplateListRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private TemplateListRequest() {
      portfolioId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TemplateListRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              portfolioId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.digitald4.budget.proto.BudgetUIProtos.internal_static_budget_TemplateListRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.digitald4.budget.proto.BudgetUIProtos.internal_static_budget_TemplateListRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.digitald4.budget.proto.BudgetUIProtos.TemplateListRequest.class, com.digitald4.budget.proto.BudgetUIProtos.TemplateListRequest.Builder.class);
    }

    private int bitField0_;
    public static final int PORTFOLIO_ID_FIELD_NUMBER = 1;
    private int portfolioId_;
    /**
     * <code>optional int32 portfolio_id = 1;</code>
     */
    public boolean hasPortfolioId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 portfolio_id = 1;</code>
     */
    public int getPortfolioId() {
      return portfolioId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, portfolioId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, portfolioId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateListRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateListRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateListRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateListRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateListRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateListRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateListRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateListRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateListRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateListRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.digitald4.budget.proto.BudgetUIProtos.TemplateListRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code budget.TemplateListRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:budget.TemplateListRequest)
        com.digitald4.budget.proto.BudgetUIProtos.TemplateListRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.digitald4.budget.proto.BudgetUIProtos.internal_static_budget_TemplateListRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.digitald4.budget.proto.BudgetUIProtos.internal_static_budget_TemplateListRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.digitald4.budget.proto.BudgetUIProtos.TemplateListRequest.class, com.digitald4.budget.proto.BudgetUIProtos.TemplateListRequest.Builder.class);
      }

      // Construct using com.digitald4.budget.proto.BudgetUIProtos.TemplateListRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        portfolioId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.digitald4.budget.proto.BudgetUIProtos.internal_static_budget_TemplateListRequest_descriptor;
      }

      public com.digitald4.budget.proto.BudgetUIProtos.TemplateListRequest getDefaultInstanceForType() {
        return com.digitald4.budget.proto.BudgetUIProtos.TemplateListRequest.getDefaultInstance();
      }

      public com.digitald4.budget.proto.BudgetUIProtos.TemplateListRequest build() {
        com.digitald4.budget.proto.BudgetUIProtos.TemplateListRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.digitald4.budget.proto.BudgetUIProtos.TemplateListRequest buildPartial() {
        com.digitald4.budget.proto.BudgetUIProtos.TemplateListRequest result = new com.digitald4.budget.proto.BudgetUIProtos.TemplateListRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.portfolioId_ = portfolioId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.digitald4.budget.proto.BudgetUIProtos.TemplateListRequest) {
          return mergeFrom((com.digitald4.budget.proto.BudgetUIProtos.TemplateListRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.digitald4.budget.proto.BudgetUIProtos.TemplateListRequest other) {
        if (other == com.digitald4.budget.proto.BudgetUIProtos.TemplateListRequest.getDefaultInstance()) return this;
        if (other.hasPortfolioId()) {
          setPortfolioId(other.getPortfolioId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.digitald4.budget.proto.BudgetUIProtos.TemplateListRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.digitald4.budget.proto.BudgetUIProtos.TemplateListRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int portfolioId_ ;
      /**
       * <code>optional int32 portfolio_id = 1;</code>
       */
      public boolean hasPortfolioId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 portfolio_id = 1;</code>
       */
      public int getPortfolioId() {
        return portfolioId_;
      }
      /**
       * <code>optional int32 portfolio_id = 1;</code>
       */
      public Builder setPortfolioId(int value) {
        bitField0_ |= 0x00000001;
        portfolioId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 portfolio_id = 1;</code>
       */
      public Builder clearPortfolioId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        portfolioId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:budget.TemplateListRequest)
    }

    // @@protoc_insertion_point(class_scope:budget.TemplateListRequest)
    private static final com.digitald4.budget.proto.BudgetUIProtos.TemplateListRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.digitald4.budget.proto.BudgetUIProtos.TemplateListRequest();
    }

    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateListRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<TemplateListRequest>
        PARSER = new com.google.protobuf.AbstractParser<TemplateListRequest>() {
      public TemplateListRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new TemplateListRequest(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<TemplateListRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TemplateListRequest> getParserForType() {
      return PARSER;
    }

    public com.digitald4.budget.proto.BudgetUIProtos.TemplateListRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TemplateGetRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:budget.TemplateGetRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 template_id = 1;</code>
     */
    boolean hasTemplateId();
    /**
     * <code>optional int32 template_id = 1;</code>
     */
    int getTemplateId();
  }
  /**
   * Protobuf type {@code budget.TemplateGetRequest}
   */
  public  static final class TemplateGetRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:budget.TemplateGetRequest)
      TemplateGetRequestOrBuilder {
    // Use TemplateGetRequest.newBuilder() to construct.
    private TemplateGetRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private TemplateGetRequest() {
      templateId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TemplateGetRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              templateId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.digitald4.budget.proto.BudgetUIProtos.internal_static_budget_TemplateGetRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.digitald4.budget.proto.BudgetUIProtos.internal_static_budget_TemplateGetRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.digitald4.budget.proto.BudgetUIProtos.TemplateGetRequest.class, com.digitald4.budget.proto.BudgetUIProtos.TemplateGetRequest.Builder.class);
    }

    private int bitField0_;
    public static final int TEMPLATE_ID_FIELD_NUMBER = 1;
    private int templateId_;
    /**
     * <code>optional int32 template_id = 1;</code>
     */
    public boolean hasTemplateId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 template_id = 1;</code>
     */
    public int getTemplateId() {
      return templateId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, templateId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, templateId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateGetRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateGetRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateGetRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateGetRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateGetRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateGetRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateGetRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateGetRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateGetRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateGetRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.digitald4.budget.proto.BudgetUIProtos.TemplateGetRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code budget.TemplateGetRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:budget.TemplateGetRequest)
        com.digitald4.budget.proto.BudgetUIProtos.TemplateGetRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.digitald4.budget.proto.BudgetUIProtos.internal_static_budget_TemplateGetRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.digitald4.budget.proto.BudgetUIProtos.internal_static_budget_TemplateGetRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.digitald4.budget.proto.BudgetUIProtos.TemplateGetRequest.class, com.digitald4.budget.proto.BudgetUIProtos.TemplateGetRequest.Builder.class);
      }

      // Construct using com.digitald4.budget.proto.BudgetUIProtos.TemplateGetRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        templateId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.digitald4.budget.proto.BudgetUIProtos.internal_static_budget_TemplateGetRequest_descriptor;
      }

      public com.digitald4.budget.proto.BudgetUIProtos.TemplateGetRequest getDefaultInstanceForType() {
        return com.digitald4.budget.proto.BudgetUIProtos.TemplateGetRequest.getDefaultInstance();
      }

      public com.digitald4.budget.proto.BudgetUIProtos.TemplateGetRequest build() {
        com.digitald4.budget.proto.BudgetUIProtos.TemplateGetRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.digitald4.budget.proto.BudgetUIProtos.TemplateGetRequest buildPartial() {
        com.digitald4.budget.proto.BudgetUIProtos.TemplateGetRequest result = new com.digitald4.budget.proto.BudgetUIProtos.TemplateGetRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.templateId_ = templateId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.digitald4.budget.proto.BudgetUIProtos.TemplateGetRequest) {
          return mergeFrom((com.digitald4.budget.proto.BudgetUIProtos.TemplateGetRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.digitald4.budget.proto.BudgetUIProtos.TemplateGetRequest other) {
        if (other == com.digitald4.budget.proto.BudgetUIProtos.TemplateGetRequest.getDefaultInstance()) return this;
        if (other.hasTemplateId()) {
          setTemplateId(other.getTemplateId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.digitald4.budget.proto.BudgetUIProtos.TemplateGetRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.digitald4.budget.proto.BudgetUIProtos.TemplateGetRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int templateId_ ;
      /**
       * <code>optional int32 template_id = 1;</code>
       */
      public boolean hasTemplateId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 template_id = 1;</code>
       */
      public int getTemplateId() {
        return templateId_;
      }
      /**
       * <code>optional int32 template_id = 1;</code>
       */
      public Builder setTemplateId(int value) {
        bitField0_ |= 0x00000001;
        templateId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 template_id = 1;</code>
       */
      public Builder clearTemplateId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        templateId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:budget.TemplateGetRequest)
    }

    // @@protoc_insertion_point(class_scope:budget.TemplateGetRequest)
    private static final com.digitald4.budget.proto.BudgetUIProtos.TemplateGetRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.digitald4.budget.proto.BudgetUIProtos.TemplateGetRequest();
    }

    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateGetRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<TemplateGetRequest>
        PARSER = new com.google.protobuf.AbstractParser<TemplateGetRequest>() {
      public TemplateGetRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new TemplateGetRequest(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<TemplateGetRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TemplateGetRequest> getParserForType() {
      return PARSER;
    }

    public com.digitald4.budget.proto.BudgetUIProtos.TemplateGetRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TemplateCreateRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:budget.TemplateCreateRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .budget.TemplateUI template = 1;</code>
     */
    boolean hasTemplate();
    /**
     * <code>optional .budget.TemplateUI template = 1;</code>
     */
    com.digitald4.budget.proto.BudgetUIProtos.TemplateUI getTemplate();
    /**
     * <code>optional .budget.TemplateUI template = 1;</code>
     */
    com.digitald4.budget.proto.BudgetUIProtos.TemplateUIOrBuilder getTemplateOrBuilder();
  }
  /**
   * Protobuf type {@code budget.TemplateCreateRequest}
   */
  public  static final class TemplateCreateRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:budget.TemplateCreateRequest)
      TemplateCreateRequestOrBuilder {
    // Use TemplateCreateRequest.newBuilder() to construct.
    private TemplateCreateRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private TemplateCreateRequest() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TemplateCreateRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.digitald4.budget.proto.BudgetUIProtos.TemplateUI.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = template_.toBuilder();
              }
              template_ = input.readMessage(com.digitald4.budget.proto.BudgetUIProtos.TemplateUI.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(template_);
                template_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.digitald4.budget.proto.BudgetUIProtos.internal_static_budget_TemplateCreateRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.digitald4.budget.proto.BudgetUIProtos.internal_static_budget_TemplateCreateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.digitald4.budget.proto.BudgetUIProtos.TemplateCreateRequest.class, com.digitald4.budget.proto.BudgetUIProtos.TemplateCreateRequest.Builder.class);
    }

    private int bitField0_;
    public static final int TEMPLATE_FIELD_NUMBER = 1;
    private com.digitald4.budget.proto.BudgetUIProtos.TemplateUI template_;
    /**
     * <code>optional .budget.TemplateUI template = 1;</code>
     */
    public boolean hasTemplate() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .budget.TemplateUI template = 1;</code>
     */
    public com.digitald4.budget.proto.BudgetUIProtos.TemplateUI getTemplate() {
      return template_ == null ? com.digitald4.budget.proto.BudgetUIProtos.TemplateUI.getDefaultInstance() : template_;
    }
    /**
     * <code>optional .budget.TemplateUI template = 1;</code>
     */
    public com.digitald4.budget.proto.BudgetUIProtos.TemplateUIOrBuilder getTemplateOrBuilder() {
      return template_ == null ? com.digitald4.budget.proto.BudgetUIProtos.TemplateUI.getDefaultInstance() : template_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getTemplate());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getTemplate());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateCreateRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateCreateRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateCreateRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateCreateRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateCreateRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateCreateRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateCreateRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateCreateRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateCreateRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateCreateRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.digitald4.budget.proto.BudgetUIProtos.TemplateCreateRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code budget.TemplateCreateRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:budget.TemplateCreateRequest)
        com.digitald4.budget.proto.BudgetUIProtos.TemplateCreateRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.digitald4.budget.proto.BudgetUIProtos.internal_static_budget_TemplateCreateRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.digitald4.budget.proto.BudgetUIProtos.internal_static_budget_TemplateCreateRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.digitald4.budget.proto.BudgetUIProtos.TemplateCreateRequest.class, com.digitald4.budget.proto.BudgetUIProtos.TemplateCreateRequest.Builder.class);
      }

      // Construct using com.digitald4.budget.proto.BudgetUIProtos.TemplateCreateRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getTemplateFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (templateBuilder_ == null) {
          template_ = null;
        } else {
          templateBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.digitald4.budget.proto.BudgetUIProtos.internal_static_budget_TemplateCreateRequest_descriptor;
      }

      public com.digitald4.budget.proto.BudgetUIProtos.TemplateCreateRequest getDefaultInstanceForType() {
        return com.digitald4.budget.proto.BudgetUIProtos.TemplateCreateRequest.getDefaultInstance();
      }

      public com.digitald4.budget.proto.BudgetUIProtos.TemplateCreateRequest build() {
        com.digitald4.budget.proto.BudgetUIProtos.TemplateCreateRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.digitald4.budget.proto.BudgetUIProtos.TemplateCreateRequest buildPartial() {
        com.digitald4.budget.proto.BudgetUIProtos.TemplateCreateRequest result = new com.digitald4.budget.proto.BudgetUIProtos.TemplateCreateRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (templateBuilder_ == null) {
          result.template_ = template_;
        } else {
          result.template_ = templateBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.digitald4.budget.proto.BudgetUIProtos.TemplateCreateRequest) {
          return mergeFrom((com.digitald4.budget.proto.BudgetUIProtos.TemplateCreateRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.digitald4.budget.proto.BudgetUIProtos.TemplateCreateRequest other) {
        if (other == com.digitald4.budget.proto.BudgetUIProtos.TemplateCreateRequest.getDefaultInstance()) return this;
        if (other.hasTemplate()) {
          mergeTemplate(other.getTemplate());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.digitald4.budget.proto.BudgetUIProtos.TemplateCreateRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.digitald4.budget.proto.BudgetUIProtos.TemplateCreateRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.digitald4.budget.proto.BudgetUIProtos.TemplateUI template_ = null;
      private com.google.protobuf.SingleFieldBuilder<
          com.digitald4.budget.proto.BudgetUIProtos.TemplateUI, com.digitald4.budget.proto.BudgetUIProtos.TemplateUI.Builder, com.digitald4.budget.proto.BudgetUIProtos.TemplateUIOrBuilder> templateBuilder_;
      /**
       * <code>optional .budget.TemplateUI template = 1;</code>
       */
      public boolean hasTemplate() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .budget.TemplateUI template = 1;</code>
       */
      public com.digitald4.budget.proto.BudgetUIProtos.TemplateUI getTemplate() {
        if (templateBuilder_ == null) {
          return template_ == null ? com.digitald4.budget.proto.BudgetUIProtos.TemplateUI.getDefaultInstance() : template_;
        } else {
          return templateBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .budget.TemplateUI template = 1;</code>
       */
      public Builder setTemplate(com.digitald4.budget.proto.BudgetUIProtos.TemplateUI value) {
        if (templateBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          template_ = value;
          onChanged();
        } else {
          templateBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .budget.TemplateUI template = 1;</code>
       */
      public Builder setTemplate(
          com.digitald4.budget.proto.BudgetUIProtos.TemplateUI.Builder builderForValue) {
        if (templateBuilder_ == null) {
          template_ = builderForValue.build();
          onChanged();
        } else {
          templateBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .budget.TemplateUI template = 1;</code>
       */
      public Builder mergeTemplate(com.digitald4.budget.proto.BudgetUIProtos.TemplateUI value) {
        if (templateBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              template_ != null &&
              template_ != com.digitald4.budget.proto.BudgetUIProtos.TemplateUI.getDefaultInstance()) {
            template_ =
              com.digitald4.budget.proto.BudgetUIProtos.TemplateUI.newBuilder(template_).mergeFrom(value).buildPartial();
          } else {
            template_ = value;
          }
          onChanged();
        } else {
          templateBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .budget.TemplateUI template = 1;</code>
       */
      public Builder clearTemplate() {
        if (templateBuilder_ == null) {
          template_ = null;
          onChanged();
        } else {
          templateBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .budget.TemplateUI template = 1;</code>
       */
      public com.digitald4.budget.proto.BudgetUIProtos.TemplateUI.Builder getTemplateBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getTemplateFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .budget.TemplateUI template = 1;</code>
       */
      public com.digitald4.budget.proto.BudgetUIProtos.TemplateUIOrBuilder getTemplateOrBuilder() {
        if (templateBuilder_ != null) {
          return templateBuilder_.getMessageOrBuilder();
        } else {
          return template_ == null ?
              com.digitald4.budget.proto.BudgetUIProtos.TemplateUI.getDefaultInstance() : template_;
        }
      }
      /**
       * <code>optional .budget.TemplateUI template = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.digitald4.budget.proto.BudgetUIProtos.TemplateUI, com.digitald4.budget.proto.BudgetUIProtos.TemplateUI.Builder, com.digitald4.budget.proto.BudgetUIProtos.TemplateUIOrBuilder> 
          getTemplateFieldBuilder() {
        if (templateBuilder_ == null) {
          templateBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.digitald4.budget.proto.BudgetUIProtos.TemplateUI, com.digitald4.budget.proto.BudgetUIProtos.TemplateUI.Builder, com.digitald4.budget.proto.BudgetUIProtos.TemplateUIOrBuilder>(
                  getTemplate(),
                  getParentForChildren(),
                  isClean());
          template_ = null;
        }
        return templateBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:budget.TemplateCreateRequest)
    }

    // @@protoc_insertion_point(class_scope:budget.TemplateCreateRequest)
    private static final com.digitald4.budget.proto.BudgetUIProtos.TemplateCreateRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.digitald4.budget.proto.BudgetUIProtos.TemplateCreateRequest();
    }

    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateCreateRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<TemplateCreateRequest>
        PARSER = new com.google.protobuf.AbstractParser<TemplateCreateRequest>() {
      public TemplateCreateRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new TemplateCreateRequest(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<TemplateCreateRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TemplateCreateRequest> getParserForType() {
      return PARSER;
    }

    public com.digitald4.budget.proto.BudgetUIProtos.TemplateCreateRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TemplateDeleteRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:budget.TemplateDeleteRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 template_id = 1;</code>
     */
    boolean hasTemplateId();
    /**
     * <code>optional int32 template_id = 1;</code>
     */
    int getTemplateId();
  }
  /**
   * Protobuf type {@code budget.TemplateDeleteRequest}
   */
  public  static final class TemplateDeleteRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:budget.TemplateDeleteRequest)
      TemplateDeleteRequestOrBuilder {
    // Use TemplateDeleteRequest.newBuilder() to construct.
    private TemplateDeleteRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private TemplateDeleteRequest() {
      templateId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TemplateDeleteRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              templateId_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.digitald4.budget.proto.BudgetUIProtos.internal_static_budget_TemplateDeleteRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.digitald4.budget.proto.BudgetUIProtos.internal_static_budget_TemplateDeleteRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.digitald4.budget.proto.BudgetUIProtos.TemplateDeleteRequest.class, com.digitald4.budget.proto.BudgetUIProtos.TemplateDeleteRequest.Builder.class);
    }

    private int bitField0_;
    public static final int TEMPLATE_ID_FIELD_NUMBER = 1;
    private int templateId_;
    /**
     * <code>optional int32 template_id = 1;</code>
     */
    public boolean hasTemplateId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 template_id = 1;</code>
     */
    public int getTemplateId() {
      return templateId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, templateId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, templateId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateDeleteRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateDeleteRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateDeleteRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateDeleteRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateDeleteRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateDeleteRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateDeleteRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateDeleteRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateDeleteRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateDeleteRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.digitald4.budget.proto.BudgetUIProtos.TemplateDeleteRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code budget.TemplateDeleteRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:budget.TemplateDeleteRequest)
        com.digitald4.budget.proto.BudgetUIProtos.TemplateDeleteRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.digitald4.budget.proto.BudgetUIProtos.internal_static_budget_TemplateDeleteRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.digitald4.budget.proto.BudgetUIProtos.internal_static_budget_TemplateDeleteRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.digitald4.budget.proto.BudgetUIProtos.TemplateDeleteRequest.class, com.digitald4.budget.proto.BudgetUIProtos.TemplateDeleteRequest.Builder.class);
      }

      // Construct using com.digitald4.budget.proto.BudgetUIProtos.TemplateDeleteRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        templateId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.digitald4.budget.proto.BudgetUIProtos.internal_static_budget_TemplateDeleteRequest_descriptor;
      }

      public com.digitald4.budget.proto.BudgetUIProtos.TemplateDeleteRequest getDefaultInstanceForType() {
        return com.digitald4.budget.proto.BudgetUIProtos.TemplateDeleteRequest.getDefaultInstance();
      }

      public com.digitald4.budget.proto.BudgetUIProtos.TemplateDeleteRequest build() {
        com.digitald4.budget.proto.BudgetUIProtos.TemplateDeleteRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.digitald4.budget.proto.BudgetUIProtos.TemplateDeleteRequest buildPartial() {
        com.digitald4.budget.proto.BudgetUIProtos.TemplateDeleteRequest result = new com.digitald4.budget.proto.BudgetUIProtos.TemplateDeleteRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.templateId_ = templateId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.digitald4.budget.proto.BudgetUIProtos.TemplateDeleteRequest) {
          return mergeFrom((com.digitald4.budget.proto.BudgetUIProtos.TemplateDeleteRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.digitald4.budget.proto.BudgetUIProtos.TemplateDeleteRequest other) {
        if (other == com.digitald4.budget.proto.BudgetUIProtos.TemplateDeleteRequest.getDefaultInstance()) return this;
        if (other.hasTemplateId()) {
          setTemplateId(other.getTemplateId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.digitald4.budget.proto.BudgetUIProtos.TemplateDeleteRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.digitald4.budget.proto.BudgetUIProtos.TemplateDeleteRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int templateId_ ;
      /**
       * <code>optional int32 template_id = 1;</code>
       */
      public boolean hasTemplateId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 template_id = 1;</code>
       */
      public int getTemplateId() {
        return templateId_;
      }
      /**
       * <code>optional int32 template_id = 1;</code>
       */
      public Builder setTemplateId(int value) {
        bitField0_ |= 0x00000001;
        templateId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 template_id = 1;</code>
       */
      public Builder clearTemplateId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        templateId_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:budget.TemplateDeleteRequest)
    }

    // @@protoc_insertion_point(class_scope:budget.TemplateDeleteRequest)
    private static final com.digitald4.budget.proto.BudgetUIProtos.TemplateDeleteRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.digitald4.budget.proto.BudgetUIProtos.TemplateDeleteRequest();
    }

    public static com.digitald4.budget.proto.BudgetUIProtos.TemplateDeleteRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<TemplateDeleteRequest>
        PARSER = new com.google.protobuf.AbstractParser<TemplateDeleteRequest>() {
      public TemplateDeleteRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new TemplateDeleteRequest(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<TemplateDeleteRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TemplateDeleteRequest> getParserForType() {
      return PARSER;
    }

    public com.digitald4.budget.proto.BudgetUIProtos.TemplateDeleteRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_budget_TemplateUI_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_budget_TemplateUI_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_budget_TemplateListRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_budget_TemplateListRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_budget_TemplateGetRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_budget_TemplateGetRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_budget_TemplateCreateRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_budget_TemplateCreateRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_budget_TemplateDeleteRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_budget_TemplateDeleteRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024conf/budget_ui.proto\022\006budget\"Q\n\nTempla" +
      "teUI\022\n\n\002id\030\001 \001(\005\022\024\n\014portfolio_id\030\002 \001(\005\022\014" +
      "\n\004name\030\003 \001(\t\022\023\n\013description\030\004 \001(\t\"+\n\023Tem" +
      "plateListRequest\022\024\n\014portfolio_id\030\001 \001(\005\")" +
      "\n\022TemplateGetRequest\022\023\n\013template_id\030\001 \001(" +
      "\005\"=\n\025TemplateCreateRequest\022$\n\010template\030\001" +
      " \001(\0132\022.budget.TemplateUI\",\n\025TemplateDele" +
      "teRequest\022\023\n\013template_id\030\001 \001(\005B,\n\032com.di" +
      "gitald4.budget.protoB\016BudgetUIProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_budget_TemplateUI_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_budget_TemplateUI_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_budget_TemplateUI_descriptor,
        new java.lang.String[] { "Id", "PortfolioId", "Name", "Description", });
    internal_static_budget_TemplateListRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_budget_TemplateListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_budget_TemplateListRequest_descriptor,
        new java.lang.String[] { "PortfolioId", });
    internal_static_budget_TemplateGetRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_budget_TemplateGetRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_budget_TemplateGetRequest_descriptor,
        new java.lang.String[] { "TemplateId", });
    internal_static_budget_TemplateCreateRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_budget_TemplateCreateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_budget_TemplateCreateRequest_descriptor,
        new java.lang.String[] { "Template", });
    internal_static_budget_TemplateDeleteRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_budget_TemplateDeleteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_budget_TemplateDeleteRequest_descriptor,
        new java.lang.String[] { "TemplateId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
