/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.budget.BillCreateRequest');

goog.require('jspb.Message');
goog.require('proto.budget.BillUI');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.budget.BillCreateRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.budget.BillCreateRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.budget.BillCreateRequest.displayName = 'proto.budget.BillCreateRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.budget.BillCreateRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.budget.BillCreateRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.budget.BillCreateRequest} msg The msg instance to transform.
 * @return {!Object}
 */
proto.budget.BillCreateRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    bill: (f = msg.getBill()) && proto.budget.BillUI.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.budget.BillCreateRequest} The clone.
 */
proto.budget.BillCreateRequest.prototype.cloneMessage = function() {
  return /** @type {!proto.budget.BillCreateRequest} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional BillUI bill = 1;
 * @return {proto.budget.BillUI}
 */
proto.budget.BillCreateRequest.prototype.getBill = function() {
  return /** @type{proto.budget.BillUI} */ (
    jspb.Message.getWrapperField(this, proto.budget.BillUI, 1));
};


/** @param {proto.budget.BillUI|undefined} value  */
proto.budget.BillCreateRequest.prototype.setBill = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.budget.BillCreateRequest.prototype.clearBill = function() {
  this.setBill(undefined);
};


