/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.budget.BillUI');
goog.provide('proto.budget.BillUI.PaymentStatusUI');
goog.provide('proto.budget.BillUI.TransactionUI');

goog.require('jspb.Message');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.budget.BillUI = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.budget.BillUI.repeatedFields_, null);
};
goog.inherits(proto.budget.BillUI, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.budget.BillUI.displayName = 'proto.budget.BillUI';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.budget.BillUI.repeatedFields_ = [12];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.budget.BillUI.prototype.toObject = function(opt_includeInstance) {
  return proto.budget.BillUI.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.budget.BillUI} msg The msg instance to transform.
 * @return {!Object}
 */
proto.budget.BillUI.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getField(msg, 1),
    portfolioId: jspb.Message.getField(msg, 2),
    accountId: jspb.Message.getField(msg, 3),
    templateId: jspb.Message.getField(msg, 4),
    dueDate: jspb.Message.getField(msg, 5),
    name: jspb.Message.getField(msg, 6),
    paymentDate: jspb.Message.getField(msg, 7),
    amountDue: jspb.Message.getField(msg, 8),
    status: jspb.Message.getField(msg, 9),
    active: jspb.Message.getField(msg, 10),
    description: jspb.Message.getField(msg, 11),
    transactionList: jspb.Message.toObjectList(msg.getTransactionList(),
    proto.budget.BillUI.TransactionUI.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.budget.BillUI} The clone.
 */
proto.budget.BillUI.prototype.cloneMessage = function() {
  return /** @type {!proto.budget.BillUI} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional int32 id = 1;
 * @return {number?}
 */
proto.budget.BillUI.prototype.getId = function() {
  return /** @type {number?} */ (jspb.Message.getField(this, 1));
};


/** @param {number?|undefined} value  */
proto.budget.BillUI.prototype.setId = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.budget.BillUI.prototype.clearId = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * optional int32 portfolio_id = 2;
 * @return {number?}
 */
proto.budget.BillUI.prototype.getPortfolioId = function() {
  return /** @type {number?} */ (jspb.Message.getField(this, 2));
};


/** @param {number?|undefined} value  */
proto.budget.BillUI.prototype.setPortfolioId = function(value) {
  jspb.Message.setField(this, 2, value);
};


proto.budget.BillUI.prototype.clearPortfolioId = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * optional int32 account_id = 3;
 * @return {number?}
 */
proto.budget.BillUI.prototype.getAccountId = function() {
  return /** @type {number?} */ (jspb.Message.getField(this, 3));
};


/** @param {number?|undefined} value  */
proto.budget.BillUI.prototype.setAccountId = function(value) {
  jspb.Message.setField(this, 3, value);
};


proto.budget.BillUI.prototype.clearAccountId = function() {
  jspb.Message.setField(this, 3, undefined);
};


/**
 * optional int32 template_id = 4;
 * @return {number?}
 */
proto.budget.BillUI.prototype.getTemplateId = function() {
  return /** @type {number?} */ (jspb.Message.getField(this, 4));
};


/** @param {number?|undefined} value  */
proto.budget.BillUI.prototype.setTemplateId = function(value) {
  jspb.Message.setField(this, 4, value);
};


proto.budget.BillUI.prototype.clearTemplateId = function() {
  jspb.Message.setField(this, 4, undefined);
};


/**
 * optional int64 due_date = 5;
 * @return {number?}
 */
proto.budget.BillUI.prototype.getDueDate = function() {
  return /** @type {number?} */ (jspb.Message.getField(this, 5));
};


/** @param {number?|undefined} value  */
proto.budget.BillUI.prototype.setDueDate = function(value) {
  jspb.Message.setField(this, 5, value);
};


proto.budget.BillUI.prototype.clearDueDate = function() {
  jspb.Message.setField(this, 5, undefined);
};


/**
 * optional string name = 6;
 * @return {string?}
 */
proto.budget.BillUI.prototype.getName = function() {
  return /** @type {string?} */ (jspb.Message.getField(this, 6));
};


/** @param {string?|undefined} value  */
proto.budget.BillUI.prototype.setName = function(value) {
  jspb.Message.setField(this, 6, value);
};


proto.budget.BillUI.prototype.clearName = function() {
  jspb.Message.setField(this, 6, undefined);
};


/**
 * optional int64 payment_date = 7;
 * @return {number?}
 */
proto.budget.BillUI.prototype.getPaymentDate = function() {
  return /** @type {number?} */ (jspb.Message.getField(this, 7));
};


/** @param {number?|undefined} value  */
proto.budget.BillUI.prototype.setPaymentDate = function(value) {
  jspb.Message.setField(this, 7, value);
};


proto.budget.BillUI.prototype.clearPaymentDate = function() {
  jspb.Message.setField(this, 7, undefined);
};


/**
 * optional double amount_due = 8;
 * @return {number?}
 */
proto.budget.BillUI.prototype.getAmountDue = function() {
  return /** @type {number?} */ (jspb.Message.getField(this, 8));
};


/** @param {number?|undefined} value  */
proto.budget.BillUI.prototype.setAmountDue = function(value) {
  jspb.Message.setField(this, 8, value);
};


proto.budget.BillUI.prototype.clearAmountDue = function() {
  jspb.Message.setField(this, 8, undefined);
};


/**
 * optional PaymentStatusUI status = 9;
 * @return {proto.budget.BillUI.PaymentStatusUI}
 */
proto.budget.BillUI.prototype.getStatus = function() {
  return /** @type {proto.budget.BillUI.PaymentStatusUI} */ (jspb.Message.getField(this, 9));
};


/** @param {proto.budget.BillUI.PaymentStatusUI|undefined} value  */
proto.budget.BillUI.prototype.setStatus = function(value) {
  jspb.Message.setField(this, 9, value);
};


proto.budget.BillUI.prototype.clearStatus = function() {
  jspb.Message.setField(this, 9, undefined);
};


/**
 * optional bool active = 10;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean?}
 */
proto.budget.BillUI.prototype.getActive = function() {
  return /** @type {boolean?} */ (jspb.Message.getField(this, 10));
};


/** @param {boolean?|undefined} value  */
proto.budget.BillUI.prototype.setActive = function(value) {
  jspb.Message.setField(this, 10, value);
};


proto.budget.BillUI.prototype.clearActive = function() {
  jspb.Message.setField(this, 10, undefined);
};


/**
 * optional string description = 11;
 * @return {string?}
 */
proto.budget.BillUI.prototype.getDescription = function() {
  return /** @type {string?} */ (jspb.Message.getField(this, 11));
};


/** @param {string?|undefined} value  */
proto.budget.BillUI.prototype.setDescription = function(value) {
  jspb.Message.setField(this, 11, value);
};


proto.budget.BillUI.prototype.clearDescription = function() {
  jspb.Message.setField(this, 11, undefined);
};


/**
 * repeated TransactionUI transaction = 12;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.budget.BillUI.TransactionUI>}
 */
proto.budget.BillUI.prototype.getTransactionList = function() {
  return /** @type{!Array.<!proto.budget.BillUI.TransactionUI>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.budget.BillUI.TransactionUI, 12));
};


/** @param {Array.<!proto.budget.BillUI.TransactionUI>|undefined} value  */
proto.budget.BillUI.prototype.setTransactionList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 12, value);
};


proto.budget.BillUI.prototype.clearTransactionList = function() {
  this.setTransactionList([]);
};


/**
 * @enum {number}
 */
proto.budget.BillUI.PaymentStatusUI = {
  PS_UNKNOWN: 0,
  PS_NOT_SCHEDULED: 1,
  PS_SCHEDULED: 2,
  PS_PENDING: 3,
  PS_PAID: 4
};


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.budget.BillUI.TransactionUI = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.budget.BillUI.TransactionUI, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.budget.BillUI.TransactionUI.displayName = 'proto.budget.BillUI.TransactionUI';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.budget.BillUI.TransactionUI.prototype.toObject = function(opt_includeInstance) {
  return proto.budget.BillUI.TransactionUI.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.budget.BillUI.TransactionUI} msg The msg instance to transform.
 * @return {!Object}
 */
proto.budget.BillUI.TransactionUI.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getField(msg, 1),
    debitAccountId: jspb.Message.getField(msg, 2),
    amount: jspb.Message.getField(msg, 3),
    paymentDate: jspb.Message.getField(msg, 4),
    status: jspb.Message.getField(msg, 5),
    active: jspb.Message.getField(msg, 6)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.budget.BillUI.TransactionUI} The clone.
 */
proto.budget.BillUI.TransactionUI.prototype.cloneMessage = function() {
  return /** @type {!proto.budget.BillUI.TransactionUI} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional int32 id = 1;
 * @return {number?}
 */
proto.budget.BillUI.TransactionUI.prototype.getId = function() {
  return /** @type {number?} */ (jspb.Message.getField(this, 1));
};


/** @param {number?|undefined} value  */
proto.budget.BillUI.TransactionUI.prototype.setId = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.budget.BillUI.TransactionUI.prototype.clearId = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * optional int32 debit_account_id = 2;
 * @return {number?}
 */
proto.budget.BillUI.TransactionUI.prototype.getDebitAccountId = function() {
  return /** @type {number?} */ (jspb.Message.getField(this, 2));
};


/** @param {number?|undefined} value  */
proto.budget.BillUI.TransactionUI.prototype.setDebitAccountId = function(value) {
  jspb.Message.setField(this, 2, value);
};


proto.budget.BillUI.TransactionUI.prototype.clearDebitAccountId = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * optional double amount = 3;
 * @return {number?}
 */
proto.budget.BillUI.TransactionUI.prototype.getAmount = function() {
  return /** @type {number?} */ (jspb.Message.getField(this, 3));
};


/** @param {number?|undefined} value  */
proto.budget.BillUI.TransactionUI.prototype.setAmount = function(value) {
  jspb.Message.setField(this, 3, value);
};


proto.budget.BillUI.TransactionUI.prototype.clearAmount = function() {
  jspb.Message.setField(this, 3, undefined);
};


/**
 * optional int64 payment_date = 4;
 * @return {number?}
 */
proto.budget.BillUI.TransactionUI.prototype.getPaymentDate = function() {
  return /** @type {number?} */ (jspb.Message.getField(this, 4));
};


/** @param {number?|undefined} value  */
proto.budget.BillUI.TransactionUI.prototype.setPaymentDate = function(value) {
  jspb.Message.setField(this, 4, value);
};


proto.budget.BillUI.TransactionUI.prototype.clearPaymentDate = function() {
  jspb.Message.setField(this, 4, undefined);
};


/**
 * optional PaymentStatusUI status = 5;
 * @return {proto.budget.BillUI.PaymentStatusUI}
 */
proto.budget.BillUI.TransactionUI.prototype.getStatus = function() {
  return /** @type {proto.budget.BillUI.PaymentStatusUI} */ (jspb.Message.getField(this, 5));
};


/** @param {proto.budget.BillUI.PaymentStatusUI|undefined} value  */
proto.budget.BillUI.TransactionUI.prototype.setStatus = function(value) {
  jspb.Message.setField(this, 5, value);
};


proto.budget.BillUI.TransactionUI.prototype.clearStatus = function() {
  jspb.Message.setField(this, 5, undefined);
};


/**
 * optional bool active = 6;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean?}
 */
proto.budget.BillUI.TransactionUI.prototype.getActive = function() {
  return /** @type {boolean?} */ (jspb.Message.getField(this, 6));
};


/** @param {boolean?|undefined} value  */
proto.budget.BillUI.TransactionUI.prototype.setActive = function(value) {
  jspb.Message.setField(this, 6, value);
};


proto.budget.BillUI.TransactionUI.prototype.clearActive = function() {
  jspb.Message.setField(this, 6, undefined);
};


