/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.budget.PortfolioUI');
goog.provide('proto.budget.PortfolioUI.PortfolioUserUI');

goog.require('jspb.Message');

goog.forwardDeclare('proto.budget.UserRoleUI');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.budget.PortfolioUI = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.budget.PortfolioUI.repeatedFields_, null);
};
goog.inherits(proto.budget.PortfolioUI, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.budget.PortfolioUI.displayName = 'proto.budget.PortfolioUI';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.budget.PortfolioUI.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.budget.PortfolioUI.prototype.toObject = function(opt_includeInstance) {
  return proto.budget.PortfolioUI.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.budget.PortfolioUI} msg The msg instance to transform.
 * @return {!Object}
 */
proto.budget.PortfolioUI.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getField(msg, 1),
    name: jspb.Message.getField(msg, 2),
    description: jspb.Message.getField(msg, 3),
    portfolioUserList: jspb.Message.toObjectList(msg.getPortfolioUserList(),
    proto.budget.PortfolioUI.PortfolioUserUI.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.budget.PortfolioUI} The clone.
 */
proto.budget.PortfolioUI.prototype.cloneMessage = function() {
  return /** @type {!proto.budget.PortfolioUI} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional int32 id = 1;
 * @return {number?}
 */
proto.budget.PortfolioUI.prototype.getId = function() {
  return /** @type {number?} */ (jspb.Message.getField(this, 1));
};


/** @param {number?|undefined} value  */
proto.budget.PortfolioUI.prototype.setId = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.budget.PortfolioUI.prototype.clearId = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * optional string name = 2;
 * @return {string?}
 */
proto.budget.PortfolioUI.prototype.getName = function() {
  return /** @type {string?} */ (jspb.Message.getField(this, 2));
};


/** @param {string?|undefined} value  */
proto.budget.PortfolioUI.prototype.setName = function(value) {
  jspb.Message.setField(this, 2, value);
};


proto.budget.PortfolioUI.prototype.clearName = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * optional string description = 3;
 * @return {string?}
 */
proto.budget.PortfolioUI.prototype.getDescription = function() {
  return /** @type {string?} */ (jspb.Message.getField(this, 3));
};


/** @param {string?|undefined} value  */
proto.budget.PortfolioUI.prototype.setDescription = function(value) {
  jspb.Message.setField(this, 3, value);
};


proto.budget.PortfolioUI.prototype.clearDescription = function() {
  jspb.Message.setField(this, 3, undefined);
};


/**
 * repeated PortfolioUserUI portfolio_user = 4;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.budget.PortfolioUI.PortfolioUserUI>}
 */
proto.budget.PortfolioUI.prototype.getPortfolioUserList = function() {
  return /** @type{!Array.<!proto.budget.PortfolioUI.PortfolioUserUI>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.budget.PortfolioUI.PortfolioUserUI, 4));
};


/** @param {Array.<!proto.budget.PortfolioUI.PortfolioUserUI>|undefined} value  */
proto.budget.PortfolioUI.prototype.setPortfolioUserList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 4, value);
};


proto.budget.PortfolioUI.prototype.clearPortfolioUserList = function() {
  this.setPortfolioUserList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.budget.PortfolioUI.PortfolioUserUI = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.budget.PortfolioUI.PortfolioUserUI, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.budget.PortfolioUI.PortfolioUserUI.displayName = 'proto.budget.PortfolioUI.PortfolioUserUI';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.budget.PortfolioUI.PortfolioUserUI.prototype.toObject = function(opt_includeInstance) {
  return proto.budget.PortfolioUI.PortfolioUserUI.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.budget.PortfolioUI.PortfolioUserUI} msg The msg instance to transform.
 * @return {!Object}
 */
proto.budget.PortfolioUI.PortfolioUserUI.toObject = function(includeInstance, msg) {
  var f, obj = {
    userId: jspb.Message.getField(msg, 1),
    role: jspb.Message.getField(msg, 2)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.budget.PortfolioUI.PortfolioUserUI} The clone.
 */
proto.budget.PortfolioUI.PortfolioUserUI.prototype.cloneMessage = function() {
  return /** @type {!proto.budget.PortfolioUI.PortfolioUserUI} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional int32 user_id = 1;
 * @return {number?}
 */
proto.budget.PortfolioUI.PortfolioUserUI.prototype.getUserId = function() {
  return /** @type {number?} */ (jspb.Message.getField(this, 1));
};


/** @param {number?|undefined} value  */
proto.budget.PortfolioUI.PortfolioUserUI.prototype.setUserId = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.budget.PortfolioUI.PortfolioUserUI.prototype.clearUserId = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * optional UserRoleUI role = 2;
 * @return {proto.budget.UserRoleUI}
 */
proto.budget.PortfolioUI.PortfolioUserUI.prototype.getRole = function() {
  return /** @type {proto.budget.UserRoleUI} */ (jspb.Message.getField(this, 2));
};


/** @param {proto.budget.UserRoleUI|undefined} value  */
proto.budget.PortfolioUI.PortfolioUserUI.prototype.setRole = function(value) {
  jspb.Message.setField(this, 2, value);
};


proto.budget.PortfolioUI.PortfolioUserUI.prototype.clearRole = function() {
  jspb.Message.setField(this, 2, undefined);
};


