/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.budget.TemplateUI');
goog.provide('proto.budget.TemplateUI.TemplateBillUI');
goog.provide('proto.budget.TemplateUI.TemplateBillUI.TemplateTransactionUI');

goog.require('jspb.Message');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.budget.TemplateUI = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.budget.TemplateUI.repeatedFields_, null);
};
goog.inherits(proto.budget.TemplateUI, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.budget.TemplateUI.displayName = 'proto.budget.TemplateUI';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.budget.TemplateUI.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.budget.TemplateUI.prototype.toObject = function(opt_includeInstance) {
  return proto.budget.TemplateUI.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.budget.TemplateUI} msg The msg instance to transform.
 * @return {!Object}
 */
proto.budget.TemplateUI.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getField(msg, 1),
    portfolioId: jspb.Message.getField(msg, 2),
    name: jspb.Message.getField(msg, 3),
    billList: jspb.Message.toObjectList(msg.getBillList(),
    proto.budget.TemplateUI.TemplateBillUI.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.budget.TemplateUI} The clone.
 */
proto.budget.TemplateUI.prototype.cloneMessage = function() {
  return /** @type {!proto.budget.TemplateUI} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional int32 id = 1;
 * @return {number?}
 */
proto.budget.TemplateUI.prototype.getId = function() {
  return /** @type {number?} */ (jspb.Message.getField(this, 1));
};


/** @param {number?|undefined} value  */
proto.budget.TemplateUI.prototype.setId = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.budget.TemplateUI.prototype.clearId = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * optional int32 portfolio_id = 2;
 * @return {number?}
 */
proto.budget.TemplateUI.prototype.getPortfolioId = function() {
  return /** @type {number?} */ (jspb.Message.getField(this, 2));
};


/** @param {number?|undefined} value  */
proto.budget.TemplateUI.prototype.setPortfolioId = function(value) {
  jspb.Message.setField(this, 2, value);
};


proto.budget.TemplateUI.prototype.clearPortfolioId = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * optional string name = 3;
 * @return {string?}
 */
proto.budget.TemplateUI.prototype.getName = function() {
  return /** @type {string?} */ (jspb.Message.getField(this, 3));
};


/** @param {string?|undefined} value  */
proto.budget.TemplateUI.prototype.setName = function(value) {
  jspb.Message.setField(this, 3, value);
};


proto.budget.TemplateUI.prototype.clearName = function() {
  jspb.Message.setField(this, 3, undefined);
};


/**
 * repeated TemplateBillUI bill = 4;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.budget.TemplateUI.TemplateBillUI>}
 */
proto.budget.TemplateUI.prototype.getBillList = function() {
  return /** @type{!Array.<!proto.budget.TemplateUI.TemplateBillUI>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.budget.TemplateUI.TemplateBillUI, 4));
};


/** @param {Array.<!proto.budget.TemplateUI.TemplateBillUI>|undefined} value  */
proto.budget.TemplateUI.prototype.setBillList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 4, value);
};


proto.budget.TemplateUI.prototype.clearBillList = function() {
  this.setBillList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.budget.TemplateUI.TemplateBillUI = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.budget.TemplateUI.TemplateBillUI.repeatedFields_, null);
};
goog.inherits(proto.budget.TemplateUI.TemplateBillUI, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.budget.TemplateUI.TemplateBillUI.displayName = 'proto.budget.TemplateUI.TemplateBillUI';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.budget.TemplateUI.TemplateBillUI.repeatedFields_ = [5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.budget.TemplateUI.TemplateBillUI.prototype.toObject = function(opt_includeInstance) {
  return proto.budget.TemplateUI.TemplateBillUI.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.budget.TemplateUI.TemplateBillUI} msg The msg instance to transform.
 * @return {!Object}
 */
proto.budget.TemplateUI.TemplateBillUI.toObject = function(includeInstance, msg) {
  var f, obj = {
    accountId: jspb.Message.getField(msg, 1),
    dueDay: jspb.Message.getField(msg, 2),
    name: jspb.Message.getField(msg, 3),
    amountDue: jspb.Message.getField(msg, 4),
    transactionList: jspb.Message.toObjectList(msg.getTransactionList(),
    proto.budget.TemplateUI.TemplateBillUI.TemplateTransactionUI.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.budget.TemplateUI.TemplateBillUI} The clone.
 */
proto.budget.TemplateUI.TemplateBillUI.prototype.cloneMessage = function() {
  return /** @type {!proto.budget.TemplateUI.TemplateBillUI} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional int32 account_id = 1;
 * @return {number?}
 */
proto.budget.TemplateUI.TemplateBillUI.prototype.getAccountId = function() {
  return /** @type {number?} */ (jspb.Message.getField(this, 1));
};


/** @param {number?|undefined} value  */
proto.budget.TemplateUI.TemplateBillUI.prototype.setAccountId = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.budget.TemplateUI.TemplateBillUI.prototype.clearAccountId = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * optional int32 due_day = 2;
 * @return {number?}
 */
proto.budget.TemplateUI.TemplateBillUI.prototype.getDueDay = function() {
  return /** @type {number?} */ (jspb.Message.getField(this, 2));
};


/** @param {number?|undefined} value  */
proto.budget.TemplateUI.TemplateBillUI.prototype.setDueDay = function(value) {
  jspb.Message.setField(this, 2, value);
};


proto.budget.TemplateUI.TemplateBillUI.prototype.clearDueDay = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * optional string name = 3;
 * @return {string?}
 */
proto.budget.TemplateUI.TemplateBillUI.prototype.getName = function() {
  return /** @type {string?} */ (jspb.Message.getField(this, 3));
};


/** @param {string?|undefined} value  */
proto.budget.TemplateUI.TemplateBillUI.prototype.setName = function(value) {
  jspb.Message.setField(this, 3, value);
};


proto.budget.TemplateUI.TemplateBillUI.prototype.clearName = function() {
  jspb.Message.setField(this, 3, undefined);
};


/**
 * optional double amount_due = 4;
 * @return {number?}
 */
proto.budget.TemplateUI.TemplateBillUI.prototype.getAmountDue = function() {
  return /** @type {number?} */ (jspb.Message.getField(this, 4));
};


/** @param {number?|undefined} value  */
proto.budget.TemplateUI.TemplateBillUI.prototype.setAmountDue = function(value) {
  jspb.Message.setField(this, 4, value);
};


proto.budget.TemplateUI.TemplateBillUI.prototype.clearAmountDue = function() {
  jspb.Message.setField(this, 4, undefined);
};


/**
 * repeated TemplateTransactionUI transaction = 5;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.budget.TemplateUI.TemplateBillUI.TemplateTransactionUI>}
 */
proto.budget.TemplateUI.TemplateBillUI.prototype.getTransactionList = function() {
  return /** @type{!Array.<!proto.budget.TemplateUI.TemplateBillUI.TemplateTransactionUI>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.budget.TemplateUI.TemplateBillUI.TemplateTransactionUI, 5));
};


/** @param {Array.<!proto.budget.TemplateUI.TemplateBillUI.TemplateTransactionUI>|undefined} value  */
proto.budget.TemplateUI.TemplateBillUI.prototype.setTransactionList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 5, value);
};


proto.budget.TemplateUI.TemplateBillUI.prototype.clearTransactionList = function() {
  this.setTransactionList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.budget.TemplateUI.TemplateBillUI.TemplateTransactionUI = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.budget.TemplateUI.TemplateBillUI.TemplateTransactionUI, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.budget.TemplateUI.TemplateBillUI.TemplateTransactionUI.displayName = 'proto.budget.TemplateUI.TemplateBillUI.TemplateTransactionUI';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.budget.TemplateUI.TemplateBillUI.TemplateTransactionUI.prototype.toObject = function(opt_includeInstance) {
  return proto.budget.TemplateUI.TemplateBillUI.TemplateTransactionUI.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.budget.TemplateUI.TemplateBillUI.TemplateTransactionUI} msg The msg instance to transform.
 * @return {!Object}
 */
proto.budget.TemplateUI.TemplateBillUI.TemplateTransactionUI.toObject = function(includeInstance, msg) {
  var f, obj = {
    debitAccountId: jspb.Message.getField(msg, 1),
    amount: jspb.Message.getField(msg, 2)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.budget.TemplateUI.TemplateBillUI.TemplateTransactionUI} The clone.
 */
proto.budget.TemplateUI.TemplateBillUI.TemplateTransactionUI.prototype.cloneMessage = function() {
  return /** @type {!proto.budget.TemplateUI.TemplateBillUI.TemplateTransactionUI} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional int32 debit_account_id = 1;
 * @return {number?}
 */
proto.budget.TemplateUI.TemplateBillUI.TemplateTransactionUI.prototype.getDebitAccountId = function() {
  return /** @type {number?} */ (jspb.Message.getField(this, 1));
};


/** @param {number?|undefined} value  */
proto.budget.TemplateUI.TemplateBillUI.TemplateTransactionUI.prototype.setDebitAccountId = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.budget.TemplateUI.TemplateBillUI.TemplateTransactionUI.prototype.clearDebitAccountId = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * optional double amount = 2;
 * @return {number?}
 */
proto.budget.TemplateUI.TemplateBillUI.TemplateTransactionUI.prototype.getAmount = function() {
  return /** @type {number?} */ (jspb.Message.getField(this, 2));
};


/** @param {number?|undefined} value  */
proto.budget.TemplateUI.TemplateBillUI.TemplateTransactionUI.prototype.setAmount = function(value) {
  jspb.Message.setField(this, 2, value);
};


proto.budget.TemplateUI.TemplateBillUI.TemplateTransactionUI.prototype.clearAmount = function() {
  jspb.Message.setField(this, 2, undefined);
};


