CREATE OR REPLACE VIEW V_TEMPLATE AS
		SELECT TEMPLATE.*,
				TEMPLATE_BILL.ID TEMPLATE_BILL_ID, TEMPLATE_BILL.DUE_DAY, TEMPLATE_BILL.NAME_D, TEMPLATE_BILL.RANK,
				TEMPLATE_BILL.AMOUNT_DUE, TEMPLATE_BILL.ACTIVE, TEMPLATE_BILL.DESCRIPTION, TEMPLATE_BILL.ACCOUNT_ID,
				ACCOUNT.NAME ACCOUNT_NAME,
				TEMPLATE_TRANSACTION.ID TEMPLATE_TRANSACTION_ID, TEMPLATE_TRANSACTION.DEBIT_ACCOUNT_ID, TEMPLATE_TRANSACTION.AMOUNT
		FROM TEMPLATE, TEMPLATE_BILL, TEMPLATE_TRANSACTION, ACCOUNT
		WHERE TEMPLATE.ID = TEMPLATE_BILL.TEMPLATE_ID AND TEMPLATE_BILL.ID = TEMPLATE_TRANSACTION.TEMPLATE_BILL_ID
				AND TEMPLATE_BILL.ACCOUNT_ID = ACCOUNT.ID
		ORDER BY DUE_DAY, RANK, TEMPLATE_BILL_ID;
		
CREATE OR REPLACE VIEW V_PORTFOLIO AS
		SELECT PORTFOLIO.*, USER_PORTFOLIO.*
		FROM PORTFOLIO, USER_PORTFOLIO
		WHERE PORTFOLIO.ID = USER_PORTFOLIO.PORTFOLIO_ID;